name: ids-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  # Core ML/DL
  - numpy>=1.21.0,<1.25.0
  - pandas>=1.3.0,<2.1.0
  - scikit-learn>=1.0.0,<1.4.0
  - matplotlib>=3.5.0,<3.8.0
  - seaborn>=0.11.0,<0.13.0
  - tensorflow>=2.12.0,<2.15.0
  - keras>=2.12.0,<2.15.0
  - scipy>=1.7.0,<1.12.0
  - statsmodels>=0.13.0,<0.15.0

  # Data utils e balanceamento
  - imbalanced-learn>=0.9.0,<0.12.0
  - joblib>=1.1.0,<1.4.0
  - tqdm>=4.62.0,<4.67.0
  - ipython
  - jupyter

  # Análise e explicabilidade
  - shap>=0.41.0,<0.44.0
  - lime>=0.2.0.1
  - plotly>=5.3.0,<5.18.0
  - dash>=2.0.0,<2.8.0
  - dash-bootstrap-components>=1.0.0,<1.5.0

  # Otimização
  - optuna>=3.0.0
  - hyperopt>=0.2.0

  # Monitoramento e performance
  - psutil>=5.9.0
  - memory-profiler>=0.60.0
  - line-profiler>=3.5.0,<4.2.0

  # Logging e configuração
  - configparser
  - python-dotenv>=0.19.0,<1.1.0

  # Database e interface
  - sqlalchemy>=1.4.0,<2.1.0
  - flask>=2.0.0,<3.1.0
  - flask-cors>=3.0.0,<4.1.0

  # Deploy e API
  - fastapi>=0.85.0,<0.105.0
  - uvicorn>=0.18.0,<0.25.0
  - pydantic>=1.9.0,<2.6.0

  # Paralelismo
  - dask>=2022.1.0,<2023.12.0
  - ray>=2.0.0,<2.9.0

  # Segurança
  - bandit>=1.7.0,<1.8.0
  - safety>=2.3.0,<3.1.0

  # Qualidade de código
  - black>=22.0.0,<23.12.0
  - flake8>=4.0.0,<6.2.0
  - pylint>=2.12.0,<3.1.0
  - mypy>=0.930,<1.8.0

  # Testes
  - pytest>=6.2.0,<7.5.0
  - pytest-cov>=3.0.0,<4.2.0
  - pytest-mock>=3.6.0,<3.13.0

  # Exportação de relatórios
  - fpdf>=3.0.0
  - reportlab>=3.6.0

  # Visualização Jupyter (opcional)
  - notebook>=6.4.0,<7.1.0
  - ipykernel>=6.7.0,<6.28.0

  # Documentação
  - sphinx>=4.3.0,<7.2.0
  - sphinx_rtd_theme>=1.0.0,<2.1.0
  - mkdocs>=1.4.0,<1.6.0
  - mkdocs-material>=8.5.0,<9.5.0
  - mkdocstrings>=0.19.0,<0.25.0
